env:
  global:
    - LC_CTYPE=en_US.UTF-8

before_script:
- carthage bootstrap --platform ios,osx

matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode9
      script:
        - set -o pipefail
        - xcodebuild build-for-testing test-without-building -workspace TypetalkSwift.xcworkspace -scheme TypetalkSwift-iOS -configuration Release -sdk iphonesimulator -destination "name=iPhone X" ENABLE_TESTABILITY=YES | xcpretty -c
        - xcodebuild build-for-testing test-without-building -workspace TypetalkSwift.xcworkspace -scheme TypetalkSwift-Mac -configuration Release -sdk macosx ENABLE_TESTABILITY=YES | xcpretty -c
